name: Deploy React Frontend to S3

on:
  push:
    branches:
      - main  # Deploy on push to main branch

jobs:
  build-and-deploy:
    runs-on: ubuntu-latest

    steps:
      # 1️⃣ Checkout code
      - name: Checkout code
        uses: actions/checkout@v3

      # 2️⃣ Setup Node.js
      - name: Setup Node.js
        uses: actions/setup-node@v3
        with:
          node-version: 20

      # 3️⃣ Install dependencies
      - name: Install dependencies
        run: npm install

      # 4️⃣ Build React app
      - name: Build React app
        run: npm run build  # or 'npm run build' if Vite outputs dist/

      # 5️⃣ Configure AWS credentials
      - name: Configure AWS credentials
        uses: aws-actions/configure-aws-credentials@v2
        with:
          aws-access-key-id: ${{ secrets.AWS_ACCESS_KEY_ID }}
          aws-secret-access-key: ${{ secrets.AWS_SECRET_ACCESS_KEY }}
          aws-region: ap-south-1

      # 6️⃣ Sync build/dist folder to S3
      - name: Deploy to S3
        run: |
          aws s3 sync dist/ s3://personal-portfolio-frontend-project/ --delete

      # 7️⃣ (Optional) List bucket files to confirm
      - name: List S3 files
        run: aws s3 ls s3://personal-portfolio-frontend-project/
